### ISSUE TITLE
CDMConnector install from renv

### ISSUE THREAD

**Issue by dandedman** [oxford-pharmacoepi/DatabaseCharacterisation#1]
hi @catalamarti : I had a problem installing CDMConnector with renv

I think the problem is line 19 in renv.lock:
```
      "RemoteUsername": "darwin-eu-dev",
```
Either  I do not have access to that repo, or the package was moved to "darwin-eu"
So I changed it to:
```
      "RemoteUsername": "darwin-eu",
```
That worked.
(I also had a problem installing Matrix for some reason, but was able to install that manually)

**Comment by catalamarti** [comment]
Sorry @dandedman, my bad, will update the renv file to the cran version. Will ping you when it is ready

**Comment by catalamarti** [comment]
renv file updated: https://github.com/oxford-pharmacoepi/DatabaseCharacterisation/commit/e2e584f98c94906342b99dc3ac673e836637e192
